# -*- coding: utf-8 -*-
"""
Self-contained HTML report for the seven-index ASI (indices.py output):
summary table, a year-to-date chart per index (smoothed ASI with the signal
bands, overheating days, state changes, and the index close), a generated
reading of each index, and the method notes.

    python asi/indices.py > /tmp/idx.json
    python asi/report_indices.py /tmp/idx.json /tmp/report.html [--labels labels.json]

All user-facing text comes from LABELS; --labels merges a JSON file of the
same shape over it, which is how a translated report is produced without
keeping translated text in this repository.
"""
import html
import json
import sys

LABELS = {
    "lang": "en",
    "month_suffix": "",
    "title": "A-Share Sentiment — Seven Indices",
    "as_of": "Data as of {date}",
    "headline_primary": "Satellite-sleeve signal (Shanghai Composite): {state}, target {weight} invested.",
    "headline_changes": "State changes today: {items}.",
    "headline_quiet": "No index changed state today.",
    "headline_missing": "Inputs unavailable today: {items} — the affected dimensions are renormalised.",
    "table_title": "Today at a glance",
    "cols": ["Index", "Close", "Change", "ASI (5d)", "Heat", "State", "Rarity", "3-month odds", "6-month odds"],
    "charts_title": "Year to date",
    "legend": {"asi": "ASI, 5-day smoothed (left axis)", "close": "Index close (right axis)",
               "trim_band": "ASI trim band 52–75", "buy_band": "ASI add band < 28",
               "hot": "Overheating ≥ 90%", "change": "State change"},
    "reading_title": "Reading",
    "method_title": "How to read this report",
    "method": ["ASI is a 0-100 sentiment score (0 = panic, 100 = euphoria)."],
    "states": {"Ice-cold (full)": "Ice-cold (full)", "Pessimistic (add)": "Pessimistic (add)",
               "Neutral (default)": "Neutral (default)", "Optimistic (trim)": "Optimistic (trim)"},
    "reasons": {"asi": "ASI in the 52-75 band", "heat": "short-term overheating"},
    "rarity": {"3m": "about once in 3 months", "6m": "about once in 6 months", "1y": "about once a year",
               "2y": "about once in 2 years", "5y": "about once in 5 years", "10y": "about once in 10 years",
               "beyond_10y": "not seen in 10 years", "none": "common reading"},
    "side": {"low": "low", "high": "high"},
    "odds_word": {"low": "gain", "high": "decline"},
    "reading": ("ASI {sm} ({side} side, {rarity}); overheating {heat}. After similar readings the index "
                "saw a {word} over 3 months {p3}% of the time (median {m3}%) and over 6 months {p6}% "
                "(median {m6}%), from {ep} separate episodes. State: {state}{since}."),
    "since": ", since {date}",
    "trim_by": {"asi": " (entered on the ASI band)", "heat": " (entered on overheating)"},
    "short_history": " History for this index starts {date}, so its odds rest on fewer years.",
    "primary_tag": "signal",
    "na": "–",
    "footer": "Generated by asi/report_indices.py. Not investment advice.",
}


def merged_labels(path):
    labels = json.loads(json.dumps(LABELS))
    if path:
        with open(path, encoding="utf-8") as f:
            extra = json.load(f)
        for k, v in extra.items():
            if isinstance(v, dict) and isinstance(labels.get(k), dict):
                labels[k].update(v)
            else:
                labels[k] = v
    return labels


def pct(x, nd=0):
    return "–" if x is None else ("%." + str(nd) + "f%%") % x


def esc(s):
    return html.escape(str(s))


def rarity_text(L, s):
    r = s["rarity"]
    return "%s · %s" % (L["side"][r["side"]], L["rarity"][r["label"] or "none"])


def odds_text(L, s, h):
    o = s["odds"].get(h) or {}
    if o.get("win_rate") is None:
        return L["na"]
    return "%s %s" % (L["odds_word"][s["odds"]["side"]], pct(o["win_rate"]))


def state_since(s):
    trans = s["transitions_ytd"]
    return trans[-1]["date"] if trans else None


# ------------------------------------------------------------------ chart
def chart(L, s, w=720, h=240):
    pts = s["ytd"]
    if len(pts) < 2:
        return ""
    pad_l, pad_r, pad_t, pad_b = 34, 46, 12, 26
    iw, ih = w - pad_l - pad_r, h - pad_t - pad_b
    n = len(pts)
    x = lambda i: pad_l + iw * i / (n - 1)
    y = lambda v: pad_t + ih * (1 - v / 100.0)
    closes = [p["close"] for p in pts]
    lo, hi = min(closes), max(closes)
    span = (hi - lo) or 1.0
    yc = lambda c: pad_t + ih * (1 - (c - lo) / span)
    out = ['<svg viewBox="0 0 %d %d" role="img" aria-label="%s">' % (w, h, esc(s["name"]))]
    out.append('<rect class="band-trim" x="%.1f" y="%.1f" width="%.1f" height="%.1f"/>' % (pad_l, y(75), iw, y(52) - y(75)))
    out.append('<rect class="band-buy" x="%.1f" y="%.1f" width="%.1f" height="%.1f"/>' % (pad_l, y(28), iw, y(0) - y(28)))
    for v in (0, 25, 50, 75, 100):
        out.append('<line class="grid" x1="%d" x2="%d" y1="%.1f" y2="%.1f"/>' % (pad_l, w - pad_r, y(v), y(v)))
        out.append('<text class="ax" x="%d" y="%.1f" text-anchor="end">%d</text>' % (pad_l - 6, y(v) + 4, v))
    for c in (lo, hi):
        out.append('<text class="ax" x="%d" y="%.1f">%s</text>' % (w - pad_r + 6, yc(c) + 4, "{:,.0f}".format(c)))
    last_m = None
    for i, p in enumerate(pts):
        m = p["date"][5:7]
        if m != last_m:
            out.append('<text class="ax" x="%.1f" y="%d" text-anchor="middle">%s</text>' % (x(i), h - 8, str(int(m)) + L.get("month_suffix", "")))
            last_m = m
    for i, p in enumerate(pts):
        if p["heat"] is not None and p["heat"] >= 0.9:
            out.append('<rect class="hot" x="%.1f" y="%d" width="%.1f" height="5"/>' % (x(i) - iw / n / 2, pad_t - 9, max(iw / n, 1.5)))
    out.append('<polyline class="close" points="%s"/>' % " ".join("%.1f,%.1f" % (x(i), yc(p["close"])) for i, p in enumerate(pts)))
    out.append('<polyline class="asi" points="%s"/>' % " ".join("%.1f,%.1f" % (x(i), y(p["asi_sm"])) for i, p in enumerate(pts)))
    idx = {p["date"]: i for i, p in enumerate(pts)}
    for t in s["transitions_ytd"]:
        i = idx.get(t["date"])
        if i is None:
            continue
        up = t["to"] in ("Ice-cold (full)", "Pessimistic (add)")
        dn = t["to"] == "Optimistic (trim)"
        cls = "chg-add" if up else ("chg-trim" if dn else "chg-neutral")
        out.append('<circle class="%s" cx="%.1f" cy="%.1f" r="4.5"><title>%s %s → %s</title></circle>' % (
            cls, x(i), y(pts[i]["asi_sm"]), esc(t["date"]), esc(L["states"].get(t["from"], t["from"])), esc(L["states"].get(t["to"], t["to"]))))
    i = n - 1
    out.append('<circle class="now" cx="%.1f" cy="%.1f" r="4"/>' % (x(i), y(pts[i]["asi_sm"])))
    out.append('<text class="nowlbl" x="%.1f" y="%.1f" text-anchor="end">%.1f</text>' % (x(i) - 7, y(pts[i]["asi_sm"]) - 7, pts[i]["asi_sm"]))
    out.append("</svg>")
    return "".join(out)


# ------------------------------------------------------------------ page
CSS = """
:root{--bg:#f6f7f5;--card:#fff;--ink:#1d2320;--dim:#5d6660;--line:#e1e5e0;--accent:#1f6f5c;
--close:#9aa39d;--trim:#c8553d;--add:#2f6fb3;--neutral:#8a8f8b;--hot:#e0892b;
--band-trim:rgba(200,85,61,.09);--band-buy:rgba(47,111,179,.09);--up:#c8553d;--down:#2e8b57}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#141816;--card:#1c211e;--ink:#e8ece9;
--dim:#98a29c;--line:#2d3430;--accent:#5fc2a4;--close:#6b746e;--trim:#e07a62;--add:#6aa3e0;--neutral:#8a918c;
--hot:#e9a04d;--band-trim:rgba(224,122,98,.12);--band-buy:rgba(106,163,224,.12);--up:#e07a62;--down:#5fbf86}}
:root[data-theme="dark"]{--bg:#141816;--card:#1c211e;--ink:#e8ece9;--dim:#98a29c;--line:#2d3430;--accent:#5fc2a4;
--close:#6b746e;--trim:#e07a62;--add:#6aa3e0;--neutral:#8a918c;--hot:#e9a04d;--band-trim:rgba(224,122,98,.12);
--band-buy:rgba(106,163,224,.12);--up:#e07a62;--down:#5fbf86}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font-family:"Noto Sans SC","PingFang SC","Microsoft YaHei",system-ui,sans-serif;line-height:1.6}
.wrap{max-width:1040px;margin:0 auto;padding:32px 16px 56px}
h1{font-family:"Noto Serif SC",serif;font-size:clamp(24px,4vw,34px);margin:0 0 4px;text-wrap:balance}
h2{font-family:"Noto Serif SC",serif;font-size:20px;margin:36px 0 12px}
.asof{color:var(--dim);font-size:14px;font-variant-numeric:tabular-nums}
.headline{margin-top:16px;padding:14px 16px;background:var(--card);border:1px solid var(--line);
border-left:4px solid var(--accent);border-radius:8px;display:grid;gap:4px}
.headline p{margin:0}.headline .warn{color:var(--hot);font-size:14px}
.tbl{overflow-x:auto;background:var(--card);border:1px solid var(--line);border-radius:10px}
table{border-collapse:collapse;width:100%;font-size:14px;font-variant-numeric:tabular-nums}
th,td{padding:9px 12px;text-align:right;white-space:nowrap;border-bottom:1px solid var(--line)}
th{color:var(--dim);font-weight:500;font-size:12.5px}th:first-child,td:first-child{text-align:left}
tr:last-child td{border-bottom:none}
.up{color:var(--up)}.down{color:var(--down)}
.pill{display:inline-block;padding:1px 9px;border-radius:999px;font-size:12.5px;border:1px solid currentColor}
.st-trim{color:var(--trim)}.st-add{color:var(--add)}.st-neutral{color:var(--neutral)}
.tag{font-size:11px;color:var(--accent);border:1px solid var(--accent);border-radius:4px;padding:0 5px;margin-left:6px}
.grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(460px,1fr));gap:14px}
@media (max-width:520px){.grid2{grid-template-columns:1fr}}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px 14px 10px}
.card h3{margin:0;font-size:16px;display:flex;align-items:baseline;gap:8px;flex-wrap:wrap}
.card h3 .num{font-variant-numeric:tabular-nums;color:var(--dim);font-size:13px;font-weight:400}
.card p{margin:6px 0 0;font-size:13.5px;color:var(--dim)}
svg{width:100%;height:auto;display:block;margin-top:8px}
svg .grid{stroke:var(--line);stroke-width:1}svg .ax{fill:var(--dim);font-size:10.5px}
svg .band-trim{fill:var(--band-trim)}svg .band-buy{fill:var(--band-buy)}
svg .asi{fill:none;stroke:var(--accent);stroke-width:2.2;stroke-linejoin:round}
svg .close{fill:none;stroke:var(--close);stroke-width:1.3;stroke-dasharray:3 3}
svg .hot{fill:var(--hot)}svg .chg-trim{fill:var(--trim)}svg .chg-add{fill:var(--add)}
svg .chg-neutral{fill:var(--card);stroke:var(--neutral);stroke-width:2}
svg .now{fill:var(--accent);stroke:var(--card);stroke-width:2}svg .nowlbl{fill:var(--ink);font-size:11px;font-weight:600}
.legend{display:flex;flex-wrap:wrap;gap:6px 16px;font-size:12.5px;color:var(--dim);margin-bottom:10px}
.legend i{display:inline-block;width:18px;height:10px;border-radius:2px;margin-right:6px;vertical-align:middle}
.method{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:6px 18px}
.method p,.method li{font-size:14px;max-width:72ch}.method h4{margin:16px 0 4px;font-size:14.5px}
footer{margin-top:28px;color:var(--dim);font-size:12.5px}
"""


def state_class(st):
    return {"Optimistic (trim)": "st-trim", "Pessimistic (add)": "st-add", "Ice-cold (full)": "st-add"}.get(st, "st-neutral")


def render(data, L):
    idx = data["indices"]
    prim = next((s for s in idx if s["primary"]), idx[0])
    o = ['<!doctype html><html lang="%s"><head><meta charset="utf-8">' % esc(L["lang"]),
         '<meta name="viewport" content="width=device-width,initial-scale=1">',
         '<title>%s</title>' % esc(L["title"]),
         '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&family=Noto+Serif+SC:wght@700&display=swap">',
         "<style>%s</style></head><body><div class=\"wrap\">" % CSS,
         "<h1>%s</h1>" % esc(L["title"]),
         '<div class="asof">%s</div>' % esc(L["as_of"].format(date=data["as_of"]))]
    o.append('<div class="headline"><p>%s</p>' % esc(L["headline_primary"].format(
        state=L["states"].get(prim["state"], prim["state"]), weight=pct(prim["satellite_target_weight"] * 100))))
    changes = [s for s in idx if s["triggered"]]
    if changes:
        items = "; ".join("%s %s → %s%s" % (s["name"], L["states"].get(s["prior_state"], s["prior_state"]),
                                             L["states"].get(s["state"], s["state"]),
                                             (" (" + L["reasons"][s["trigger_reason"]] + ")") if s["trigger_reason"] else "")
                          for s in changes)
        o.append("<p><b>%s</b></p>" % esc(L["headline_changes"].format(items=items)))
    else:
        o.append("<p>%s</p>" % esc(L["headline_quiet"]))
    missing = sorted({m for s in idx for m in s["missing_inputs"]})
    if missing:
        o.append('<p class="warn">%s</p>' % esc(L["headline_missing"].format(items=", ".join(missing))))
    o.append("</div>")

    o.append("<h2>%s</h2><div class=\"tbl\"><table><thead><tr>%s</tr></thead><tbody>" % (
        esc(L["table_title"]), "".join("<th>%s</th>" % esc(c) for c in L["cols"])))
    for s in idx:
        ch = s["change_pct"]
        o.append("<tr><td>%s%s</td><td>%s</td><td class=\"%s\">%+.2f%%</td><td>%.1f</td><td>%s</td>"
                 "<td><span class=\"pill %s\">%s</span></td><td>%s</td><td>%s</td><td>%s</td></tr>" % (
                     esc(s["name"]), ('<span class="tag">%s</span>' % esc(L["primary_tag"])) if s["primary"] else "",
                     "{:,.2f}".format(s["close"]), "up" if ch > 0 else ("down" if ch < 0 else ""), ch,
                     s["asi_smoothed_5d"], pct(s["heat"] * 100 if s["heat"] is not None else None),
                     state_class(s["state"]), esc(L["states"].get(s["state"], s["state"])),
                     esc(rarity_text(L, s)), esc(odds_text(L, s, "3m")), esc(odds_text(L, s, "6m"))))
    o.append("</tbody></table></div>")

    lg = L["legend"]
    o.append("<h2>%s</h2>" % esc(L["charts_title"]))
    o.append('<div class="legend"><span><i style="background:var(--accent)"></i>%s</span>'
             '<span><i style="background:var(--close)"></i>%s</span>'
             '<span><i style="background:var(--band-trim);border:1px solid var(--trim)"></i>%s</span>'
             '<span><i style="background:var(--band-buy);border:1px solid var(--add)"></i>%s</span>'
             '<span><i style="background:var(--hot)"></i>%s</span>'
             '<span><i style="background:var(--trim);border-radius:50%%;width:10px"></i>%s</span></div>' % tuple(
                 esc(lg[k]) for k in ("asi", "close", "trim_band", "buy_band", "hot", "change")))
    o.append('<div class="grid2">')
    for s in idx:
        since = state_since(s)
        o_ = s["odds"]
        reading = L["reading"].format(
            sm="%.1f" % s["asi_smoothed_5d"], side=L["side"][s["rarity"]["side"]],
            rarity=L["rarity"][s["rarity"]["label"] or "none"],
            heat=pct(s["heat"] * 100 if s["heat"] is not None else None),
            word=L["odds_word"][o_["side"]],
            p3=o_["3m"]["win_rate"] if o_["3m"]["win_rate"] is not None else L["na"],
            m3="%+.1f" % o_["3m"]["median_return"] if o_["3m"]["median_return"] is not None else L["na"],
            p6=o_["6m"]["win_rate"] if o_["6m"]["win_rate"] is not None else L["na"],
            m6="%+.1f" % o_["6m"]["median_return"] if o_["6m"]["median_return"] is not None else L["na"],
            ep=o_["episodes"], state=L["states"].get(s["state"], s["state"]),
            since=L["since"].format(date=since) if since else "")
        if s["state"] == "Optimistic (trim)" and s.get("trim_by"):
            reading += L["trim_by"][s["trim_by"]]
        if s["history_start"] > "2016-12-31":
            reading += L["short_history"].format(date=s["history_start"])
        o.append('<div class="card"><h3>%s%s <span class="num">%s &nbsp;%+.2f%%</span></h3>%s<p>%s</p></div>' % (
            esc(s["name"]), ('<span class="tag">%s</span>' % esc(L["primary_tag"])) if s["primary"] else "",
            "{:,.2f}".format(s["close"]), s["change_pct"], chart(L, s), esc(reading)))
    o.append("</div>")

    o.append("<h2>%s</h2><div class=\"method\">" % esc(L["method_title"]))
    for block in L["method"]:
        if isinstance(block, dict):
            o.append("<h4>%s</h4>" % esc(block["h"]))
            if block.get("items"):
                o.append("<ul>%s</ul>" % "".join("<li>%s</li>" % esc(i) for i in block["items"]))
            if block.get("p"):
                o.append("<p>%s</p>" % esc(block["p"]))
        else:
            o.append("<p>%s</p>" % esc(block))
    o.append("</div><footer>%s</footer></div></body></html>" % esc(L["footer"]))
    return "\n".join(o)


if __name__ == "__main__":
    args = sys.argv[1:]
    labels_path = None
    if "--labels" in args:
        i = args.index("--labels")
        labels_path = args[i + 1]
        args = args[:i] + args[i + 2:]
    with open(args[0], encoding="utf-8") as f:
        data = json.load(f)
    L = merged_labels(labels_path)
    names = L.get("index_names", {})
    for s in data["indices"]:
        s["name"] = names.get(s["symbol"], s["name"])
    with open(args[1], "w", encoding="utf-8") as f:
        f.write(render(data, L))
